- name: isu-ruby is disabled
  systemd:
    name: isu-ruby
    state: stopped
    enabled: false
  become: yes

- name: isu-go is running
  systemd:
    name: isu-go
    state: started
    enabled: true
  become: yes

- name: Git checkout
  git:
    repo: https://github.com/megutamago/test-private_isu.git
    dest: /home/isucon/test-private_isu

- name: remove
  file: 
    path: /home/isucon/private_isu/webapp
    state: absent

- name: shell
  shell: mv /home/isucon/test-private_isu/webapp /home/isucon/private_isu/

- name: remove
  file: 
    path: /home/isucon/test-private_isu
    state: absent
  ignore_errors: yes

- name: isu-go is restarted
  systemd:
    name: isu-go
    state: restarted
  become: yes

- name: remove
  file: 
    path: /var/log/nginx/access.log
    state: absent
  become: yes

- name: nginx is restarted
  systemd:
    name: nginx
    state: restarted
  become: yes

- name: remove
  file: 
    path: /var/log/mysql/mysql-slow.sql
    state: absent
  become: yes

- name: mysql is restarted
  systemd:
    name: mysql
    state: restarted
  become: yes