- name: archive
  shell: tar zcvfp /home/isucon/private_isu/webapp.tar.gz /home/isucon/private_isu/webapp

- name: fetch
  fetch:
    src: /home/isucon/private_isu/webapp.tar.gz
    dest: ../files/fetch/
    flat: yes

- name: remove file
  file: 
    path: /home/isucon/private_isu/webapp.tar.gz
    state: absent

- name: fetch
  fetch:
    src: /etc/nginx/nginx.conf
    dest: ../files/fetch/
    flat: yes

#- name: create mysqldump
#  shell: mysqldump -u isuconp dbname | gzip > /home/isucon/dbname.dump.gz 
#
#- name: fetch
#  fetch:
#    src: /home/isucon/dbname.dump.gz 
#    dest: ../files/fetch/
#    flat: yes
#
#- name: remove file
#  file: 
#    path: /home/isucon/private_isu/webapp.tar.gz
#    state: absent
#  ignore_errors: yes