# Add
- name: shell
  shell: mysql -u root -pisuconp -e "alter table comments add index post_index(post_id);"
  ignore_errors: yes

- name: mysql is restarted
  systemd:
    name: mysql
    state: restarted
  become: yes

# Add
- name: shell
  shell: bash -lc "go get github.com/redis/go-redis/v8"
  args:
    chdir: /home/isucon/private_isu/webapp/golang/
  ignore_errors: yes

- name: isu-go is restarted
  systemd:
    name: isu-go
    state: restarted
  become: yes