- name: create directory
  file:
    path: /home/isucon/.ssh
    state: directory
    owner: isucon
    group: isucon
    mode: '0700'

- name: Copy isucon key
  copy:
    src: /home/user/.ssh/authorized_keys
    dest: /home/isucon/.ssh
    owner: isucon
    group: isucon
    mode: '0600'
    remote_src: yes